export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const CHANGE_THEME = 'CHANGE_THEME'
export  const DISABLED_BTN = 'DISABLED_BTN'
export  const ENABLED_BTN = 'ENABLED_BTN'
